version: '3'
services:
  # Your Node.js application
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
       - MONGODB_URI=your_mongodb_uri
        - EMAIL_USER=your_email@gmail.com
        - EMAIL_PASSWORD=your_email_password
    depends_on:
      - mongodb
    restart: unless-stopped

  # MongoDB service
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: